services:
  api:
    image: nagarroamol/expensifyapp-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ExpenseManagerDb;User Id=sa;Password=Nagarro@123;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
    ports:
      - "5000:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  react-app:
    image: nagarroamol/expensifyapp-react-app
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3001:80"
    networks:
      - app-network
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Nagarro@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Nagarro@123 -Q 'SELECT 1' -C"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=127.0.0.1:9090'
    network_mode: "host"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SERVER_HTTP_ADDR: "127.0.0.1"
    network_mode: "host"
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  db_data: