name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Docker hub login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ vars.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set working directory for a docker api
      run: |
        echo "Current working directory"
        pwd
      working-directory: ./API
    
    - name: Build the Docker image & Tag
      run: |
        docker build -t expensifyapp-api:latest .
        # docker tag expensifyapp-api:latest $API_IMAGE_NAME
        # docker tag expensifyapp-react-app:latest $APP_IMAGE_NAME
        docker images

    - name: Push Docker image to Docker hub
      run: |
        docker push ${{ vars.DOCKER_USERNAME }}/expensifyapp-api
        # docker push ${{ vars.DOCKER_USERNAME }}/expensifyapp-react-app

